kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-nas3
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sc-smb-nas3
  volumeName: pv-smb-nas3
