apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-smb-nas3
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.0.103/hatlonely_nas3/share"
  csi.storage.k8s.io/provisioner-secret-name: "smbcreds"
  csi.storage.k8s.io/provisioner-secret-namespace: "{{ .Release.Namespace }}"
  csi.storage.k8s.io/node-stage-secret-name: "smbcreds"
  csi.storage.k8s.io/node-stage-secret-namespace: "{{ .Release.Namespace }}"
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1001
  - gid=1001
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
