task:
  nav:
    description: |
      ## ops 命令

      ops --variable .cfg/dev.yaml -a run --env dev --task nav --cmd=pull
      ops --variable .cfg/dev.yaml -a run --env dev --task nav --cmd=image
      ops --variable .cfg/dev.yaml -a run --env dev --task nav --cmd=install
      ops --variable .cfg/dev.yaml -a run --env dev --task nav --cmd=password

      ## 参考链接

      - nav 代码地址: <https://github.com/xjh22222228/nav>
    args:
      cmd:
        type: string
        default: diff
        validation: x in ["pull", "diff", "image", "install", "delete", "upgrade", "status"]
    const:
      #      SECRET_NAME: nav-tls
      app: nav
      chart: helm
      version: v1.0.0
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - sh ${DEP}/ops/tool/render.sh values-adapter.yaml.tpl ${TMP}/${app}/values-adapter.yaml
      - |
        case "${cmd}" in
          "image")
            docker build -t ${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/nav:${version} docker -f docker/Dockerfile
            docker login -u ${REGISTRY_USERNAME} -p ${REGISTRY_PASSWORD} ${REGISTRY_ENDPOINT}
            docker push ${REGISTRY_ENDPOINT}/${REGISTRY_NAMESPACE}/nav:${version}
            ;;
          "diff") helm diff upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --allow-unreleased --version=${version};;
          "install") helm install -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version};;
          "upgrade") helm upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version};;
          "status") helm status -n "${NAMESPACE}" "${app}";;
          "delete") helm delete -n "${NAMESPACE}" "${app}";;
        esac
