apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent-exporter
      app.kubernetes.io/instance: qbittorrent-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent-exporter
        app.kubernetes.io/instance: qbittorrent-exporter
    spec:
      containers:
        - name: qbittorrent-exporter
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: IfNotPresent
          env:
            - name: QBITTORRENT_BASE_URL
              value: http://qbittorrent-webui
            - name: QBITTORRENT_USERNAME
              value: admin
            - name: QBITTORRENT_PASSWORD
              value: {{.Values.password}}
          ports:
            - name: metrics
              containerPort: 17871
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}