apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent-exporter
spec:
  selector:
    matchLabels:
      name: qbittorrent-exporter
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics
      honorLabels: true
      interval: 15s
      scrapeTimeout: 5s
      path: /metrics
      scheme: http
