task:
  jenkins:
    description: |
      ## ops 命令

      ops --variable .cfg/dev.yaml -a run --env dev --task jenkins --cmd=pull
      ops --variable .cfg/dev.yaml -a run --env dev --task jenkins --cmd=image
      ops --variable .cfg/dev.yaml -a run --env dev --task jenkins --cmd=install
      ops --variable .cfg/dev.yaml -a run --env dev --task jenkins --cmd=password

      ## 参考链接

      - 仓库地址: <https://artifacthub.io/packages/helm/jenkinsci/jenkins>
    args:
      cmd:
        type: string
        default: diff
        validation: x in ["pull", "diff", "install", "delete", "upgrade", "status", "password", "values", "image"]
    const:
      #      SECRET_NAME: jenkins-tls
      app: jenkins
      chart: jenkins/jenkins
      version: 4.9.1
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - sh ${DEP}/devops/tool/render.sh values-adapter.yaml.tpl ${TMP}/${app}/values-adapter.yaml
      - |
        case "${cmd}" in
          "pull") helm pull ${chart} --version=${version} && mkdir -p ${HELM_HOME}/${app} && mv ${app}-${version}.tgz ${HELM_HOME}/${app}/;;
        esac
        chart=${HELM_HOME}/${app}/${app}-${version}.tgz
        case "${cmd}" in
          "repo") helm repo add jenkins https://charts.jenkins.io/;;
          "image")
            sh ${DEP}/devops/tool/image.sh sync "docker.io" "kiwigrid" "" "" "${REGISTRY_ENDPOINT}" "${REGISTRY_NAMESPACE}" "${REGISTRY_USERNAME}" "${REGISTRY_PASSWORD}" "k8s-sidecar" "1.24.4"
            sh ${DEP}/devops/tool/image.sh sync "docker.io" "jenkins" "" "" "${REGISTRY_ENDPOINT}" "${REGISTRY_NAMESPACE}" "${REGISTRY_USERNAME}" "${REGISTRY_PASSWORD}" "jenkins" "2.426.1-jdk17"
            ;;
          "diff") helm diff upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --allow-unreleased --version=${version};;
          "install")
            helm install -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version}
            ;;
          "upgrade") helm upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version};;
          "status") helm status -n "${NAMESPACE}" "${app}";;
          "delete")
            helm delete -n "${NAMESPACE}" "${app}"
            ;;
          "password")
            echo admin
            kubectl exec --namespace ${NAMESPACE} svc/jenkins -c jenkins -- /bin/cat /run/secrets/additional/chart-admin-password; echo
            ;;
        esac
