apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{.Release.Namespace}}
  name: alist
spec:
  ingressClassName: nginx
  rules:
    - host: "{{.Values.ingress.host}}"
      http:
        paths:
          - backend:
              service:
                name: alist
                port:
                  name: alist
            path: /
            pathType: ImplementationSpecific
  {{- if .Values.ingress.tls}}
  tls:
    - secretName: {{.Values.ingress.tls}}
      hosts:
        - {{.Values.ingress.host}}
  {{- end}}
