apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: alist
  labels:
    app.kubernetes.io/instance: alist
    app.kubernetes.io/name: alist
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: alist
    app.kubernetes.io/name: alist
  ports:
    - port: 5244
      name: alist
      protocol: TCP
      targetPort: alist
