task:
  kibana:
    description: |
      ## ops 命令

      ops --variable .cfg/dev.yaml -a run --env dev --task kibana --cmd=pull
      ops --variable .cfg/dev.yaml -a run --env dev --task kibana --cmd=image
      ops --variable .cfg/dev.yaml -a run --env dev --task kibana --cmd=install
      ops --variable .cfg/dev.yaml -a run --env dev --task kibana --cmd=password

      ## 参考链接

      - 仓库地址: https://artifacthub.io/packages/helm/elastic/kibana
      - 项目地址: https://github.com/elastic/helm-charts/tree/master/kibana
    args:
      cmd:
        type: string
        default: diff
        validation: x in ["pull", "diff", "install", "delete", "upgrade", "status", "password", "values", "image"]
    const:
      SECRET_NAME: kibana-tls
      app: kibana
      chart: elastic/kibana
      version: 8.5.1
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - sh ${DEP}/ops/tool/render.sh ops/${app} ${TMP}/${app}
      - |
        case "${cmd}" in
          "pull") helm pull ${chart} --version=${version} && mkdir -p ${HELM_HOME}/${app} && mv ${app}-${version}.tgz ${HELM_HOME}/${app}/;;
        esac
        chart=${HELM_HOME}/${app}/${app}-${version}.tgz
        case "${cmd}" in
          "values") curl https://raw.githubusercontent.com/elastic/helm-charts/v${version}/${app}/values.yaml -o ops/${app}/values.yaml;;
          "image")
            sh ${DEP}/ops/tool/image.sh sync "docker.elastic.co" "kibana" "" "" "${REGISTRY_ENDPOINT}" "${REGISTRY_NAMESPACE}" "${REGISTRY_USERNAME}" "${REGISTRY_PASSWORD}" "kibana" "${version}"
            ;;
          "diff") helm diff upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --allow-unreleased --version=${version};;
          "install")
            kubectl get secret kibana -n "${NAMESPACE}" 2>/dev/null 1>&2 || kubectl create secret generic kibana -n "${NAMESPACE}" --from-literal=encryptionkey="${KIBANA_PASSWORD}"
            helm install -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version}
            ;;
          "upgrade") helm upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version};;
          "status") helm status -n "${NAMESPACE}" "${app}";;
          "delete")
            helm delete -n "${NAMESPACE}" "${app}"
            kubectl delete secret -n "${NAMESPACE}" kibana
            kubectl delete configmap -n "${NAMESPACE}" kibana-kibana-helm-scripts
            kubectl delete sa -n "${NAMESPACE}" pre-install-kibana-kibana
            kubectl delete job -n "${NAMESPACE}" pre-install-kibana-kibana
            ;;
        esac
