

ingress:
  enabled: false
  className: nginx
  tls:
    - secretName: "${SECRET_NAME}"
      hosts:
        - "${NEXTCLOUD_HOST}"
  path: /
  pathType: Prefix

nextcloud:
  host: "${NEXTCLOUD_HOST}"
  username: admin
  password: "${NEXTCLOUD_PASSWORD}"
