kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pv-smb-nas3-qbitorrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: sc-smb-nas3
  volumeName: pv-smb-nas3-qbitorrent
