task:
  jupyterhub:
    description: |
      ## ops 命令

      ops --variable .cfg/dev.yaml -a run --env dev --task jupyterhub --cmd=pull
      ops --variable .cfg/dev.yaml -a run --env dev --task jupyterhub --cmd=image
      ops --variable .cfg/dev.yaml -a run --env dev --task jupyterhub --cmd=install
      ops --variable .cfg/dev.yaml -a run --env dev --task jupyterhub --cmd=password

      ## 参考链接

      - 仓库地址: <https://artifacthub.io/packages/helm/jupyterhub/jupyterhub>
    args:
      cmd:
        type: string
        default: diff
        validation: x in ["pull", "diff", "image", "install", "delete", "upgrade", "status", "password"]
    const:
      SECRET_NAME: jupyterhub-tls
      app: jupyterhub
      chart: jupyterhub/jupyterhub
      version: 3.0.0-0.dev.git.6136.h50fe018a
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - sh ${DEP}/devops/tool/render.sh ops/${app} ${TMP}/${app}
      - |
        case "${cmd}" in
          "pull") helm pull ${chart} --version=${version} && mkdir -p ${HELM_HOME}/${app} && mv ${app}-${version}.tgz ${HELM_HOME}/${app}/;;
        esac
        chart=${HELM_HOME}/${app}/${app}-${version}.tgz
        case "${cmd}" in
          "image")
            sh ${DEP}/ops/tool/image.sh sync "docker.io" "linuxserver" "" "" "${REGISTRY_ENDPOINT}" "${REGISTRY_NAMESPACE}" "${REGISTRY_USERNAME}" "${REGISTRY_PASSWORD}" "jupyterhub" "4.5.2"
            ;;
          "diff") helm diff upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --allow-unreleased --version=${version};;
          "install") helm install -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version};;
          "upgrade") helm upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version};;
          "status") helm status -n "${NAMESPACE}" "${app}";;
          "delete") helm delete -n "${NAMESPACE}" "${app}";;
          "password") kubectl get secret --namespace "${NAMESPACE}" "${app}" -o jsonpath="{.data.jupyterhub-password}" | base64 --decode; echo
        esac
