apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: smb-nas3-aria2
spec:
  capacity:
    storage: 45Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sc-smb-nas3
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1001
    - gid=1001
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: 192.168.0.103#hatlonely_nas3/share#nas3_share_aria2
    volumeAttributes:
      source: "//192.168.0.103/hatlonely_nas3/share"
    nodeStageSecretRef:
      name: smbcreds
      namespace: {{ .Release.Namespace }}
