kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smb-nas3-aria2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: sc-smb-nas3
  volumeName: smb-nas3-aria2
