apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: aria2
  labels:
    app.kubernetes.io/instance: aria2
    app.kubernetes.io/name: aria2
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.0.191
  selector:
    app.kubernetes.io/instance: aria2
    app.kubernetes.io/name: aria2
  ports:
    - name: rpc
      port: 6800
      protocol: TCP
      targetPort: rpc
    - name: listen
      port: 16882
      protocol: TCP
      targetPort: listen
