apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: {{.Release.Namespace}}
  name: aria-exporter
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/instance: aria-exporter
    app.kubernetes.io/name: aria-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: aria-exporter
      app.kubernetes.io/name: aria-exporter
  endpoints:
    - port: metrics
      interval: 15s
      scrapeTimeout: 5s
      path: /metrics
      scheme: http
