apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: aria-exporter
  labels:
    app.kubernetes.io/instance: aria-exporter
    app.kubernetes.io/name: aria-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: aria-exporter
    app.kubernetes.io/name: aria-exporter
  ports:
    - port: 9100
      name: metrics
      protocol: TCP
      targetPort: metrics
