apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.name }}
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  size: {{ .Values.replica }}