task:
  mysql:
    description: |
      ## ops 命令

      ops --variable .cfg/dev.yaml -a run --env dev --task mysql --cmd=pull
      ops --variable .cfg/dev.yaml -a run --env dev --task mysql --cmd=image
      ops --variable .cfg/dev.yaml -a run --env dev --task mysql --cmd=install

      ## 参考链接

      - 仓库地址: <https://artifacthub.io/packages/helm/bitnami/mysql>
      - 项目地址: <https://github.com/bitnami/charts/tree/master/bitnami/mysql>
    args:
      cmd:
        type: string
        default: diff
        validation: x in ["pull", "image", "diff", "install", "delete", "upgrade", "status", "password"]
    const:
      app: mysql
      chart: bitnami/mysql
      version: 9.7.1
    step:
      - test "${K8S_CONTEXT}" == "$(kubectl config current-context)" || exit 1
      - sh ${DEP}/ops/tool/render.sh ops/${app} ${TMP}/${app}
      - |
        case "${cmd}" in
          "pull") helm pull ${chart} --version=${version} && mkdir -p ${HELM_HOME}/${app} && mv ${app}-${version}.tgz ${HELM_HOME}/${app}/;;
        esac
        chart=${HELM_HOME}/${app}/${app}-${version}.tgz
        case "${cmd}" in
          "image")
            sh ${DEP}/ops/tool/image.sh sync "docker.io" "bitnami" "" "" "${REGISTRY_ENDPOINT}" "${REGISTRY_NAMESPACE}" "${REGISTRY_USERNAME}" "${REGISTRY_PASSWORD}" "mysql" 8.0.32-debian-11-r21
            ;;
          "diff") helm diff upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --allow-unreleased --version=${version};;
          "install") helm install -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version};;
          "upgrade") helm upgrade -n "${NAMESPACE}" "${app}" "${chart}" -f "${TMP}/${app}/values-adapter.yaml" --version=${version};;
          "status") helm status -n "${NAMESPACE}" "${app}";;
          "delete")
            helm delete -n "${NAMESPACE}" "${app}"
            kubectl delete pvc -n "${NAMESPACE}" data-mysql-0
            ;;
          "password") kubectl get secret --namespace "${NAMESPACE}" "${app}" -o jsonpath="{.data.mysql-root-password}" | base64 --decode; echo
        esac
